dist: xenial
language: python
python:
  - "3.6"

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KONG_SOURCE_LOCATION=$PWD/kong
    - HELM_VERSION=v2.11.0
    - MINIKUBE_VERSION=v0.33.1
    - EDITION=community
    - KONG_PACKAGE_NAME=kong
    - KONG_CONFLICTS=kong-enterprise
    - KONG_LICENSE="ASL 2.0"
  matrix:
    - PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=amazonlinux RESTY_IMAGE_TAG=latest KONG_SOURCE=master
    - PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=amazonlinux RESTY_IMAGE_TAG=1 KONG_SOURCE=master
    - PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=amazonlinux RESTY_IMAGE_TAG=latest KONG_SOURCE=1.1.0
    - PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=amazonlinux RESTY_IMAGE_TAG=1 KONG_SOURCE=1.1.0

before_install:
  - make setup_tests >make.log 2>&1 &
  - docker pull kong/kong-build-tools:fpm || true
  - docker pull kong/kong-build-tools:test_runner || true
  - docker pull kong/kong-build-tools:test-${RESTY_IMAGE_BASE}-${RESTY_IMAGE_TAG} || true
  - docker pull kong/kong-build-tools:${RESTY_IMAGE_BASE}-${RESTY_IMAGE_TAG} || true
  - docker pull kong/kong-build-tools:kong-${RESTY_IMAGE_BASE}-${RESTY_IMAGE_TAG} || true
  - git clone --single-branch --branch ${KONG_SOURCE} https://github.com/Kong/kong.git kong

install:
  - make package-kong

before_script:
  - cat make.log
  - until kubectl get nodes 2>&1 | sed -n 2p | grep -q Ready; do sleep 5 && kubectl get nodes; done

script:
  - make test

after_success:
  - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then make build-development-image; fi
  - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then make update-docker-cache; fi

