version: '2.1'
services:
  dbs:
    image: alpine
    depends_on:
      - postgres
      - cassandra
      - redis
  kong:
    image: kong/kong-build-tools:development
    entrypoint: tail -f /dev/null
    user: ${USER:-root}
    working_dir: /kong
    volumes:
      - ${KONG_SOURCE_LOCATION:-../kong}:/kong
      - ./kong-plugin:/kong-plugin
    depends_on:
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    environment:
      LUA_PATH: /tmp/build/usr/local/share/lua/5.1/?.lua;/tmp/build/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/kong-plugin/?.lua;/kong/?.lua;;
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/build/usr/local/openresty/luajit/bin:/tmp/build/usr/local/openresty/luajit/bin;/usr/local/openresty/bin
      TEST: ${TEST:-spec/}
      KONG_PREFIX: /kong/servroot
      KONG_PLUGINS: bundled,myplugin
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: ${KONG_DATABASE:-postgres}
      KONG_TEST_DATABASE: ${KONG_DATABASE:-postgres}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong_tests}
      KONG_TEST_PG_DATABASE: ${KONG_PG_DATABASE:-kong_tests}
      KONG_CASSANDRA_CONTACT_POINTS: 127.0.0.1
      KONG_DB_UPDATE_PROPAGATION: ${KONG_DB_UPDATE_PROPAGATION:-2}
      KONG_TEST_DB_UPDATE_PROPAGATION: ${KONG_DB_UPDATE_PROPAGATION:-2}
      KONG_PG_HOST: 127.0.0.1
      KONG_TEST_PG_HOST: 127.0.0.1
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_ANONYMOUS_REPORTS: "false"
    network_mode: "host"
    restart: on-failure
  redis:
    image: redis
    network_mode: host
    restart: always
  postgres:
    image: postgres:${POSTGRES_VERSION:-9.5}
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong_tests}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    network_mode: "host"
    stdin_open: true
    tty: true
  cassandra:
    image: cassandra:${CASSANDRA_VERSION:-3.9}
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u cassandra -p cassandra \"127.0.0.1\" < /dev/null || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 12
    restart: always
